import asyncio
from plugins import NaslPlugin, PluginResult


class WafDetectionPlugin(NaslPlugin):
    PLUGIN_ID = 1306
    NAME = "Web Application Firewall Detection"
    DESCRIPTION = "Detects the presence of a Web Application Firewall (WAF) by analyzing response headers, cookies, and behavior patterns. Cloudflare, AWS WAF, ModSecurity, Akamai, F5 ASM, and others each leave distinct fingerprints."
    SOLUTION = "Ensure WAF rules are properly configured and not leaking internal information."
    CVSS_SCORE = 0
    SEVERITY = "Info"
    FAMILY = "Information Gathering"
    CVE = []
    PORTS = [80, 443]

    async def check_target(self, target: str, port: int | None = None) -> list[PluginResult]:
        results = []
        for p in ([port] if port else self.PORTS):
            for path in ["/", "/?=<script>alert(1)</script>", "/../../etc/passwd"]:
                try:
                    reader, writer = await asyncio.wait_for(
                        asyncio.open_connection(target, p), timeout=5
                    )
                    request = (
                        f"GET {path} HTTP/1.1\r\n"
                        f"Host: {target}:{p}\r\n"
                        f"User-Agent: CentraScanner/1.0\r\n"
                        f"Accept: */*\r\n"
                        f"Connection: close\r\n\r\n"
                    )
                    writer.write(request.encode())
                    await writer.drain()
                    resp = await asyncio.wait_for(reader.read(4096), timeout=5)
                    writer.close()
                    await writer.wait_closed()
                    body = resp.decode("utf-8", errors="replace")
                    waf_signatures = {
                        "Cloudflare": ["cf-ray", "__cfduid", "cloudflare"],
                        "AWS WAF": ["x-amzn-requestid", "x-amzn-ErrorType", "AWS WAF"],
                        "ModSecurity": ["Mod_Security", "NOYB", "This error was generated by Mod_Security"],
                        "Akamai": ["akamai", "AkamaiGHost", "x-akamai"],
                        "F5 ASM": ["x-asm-request-id", "x-asm-policy", "F5"],
                        "Barracuda": ["Barracuda", "barracuda"],
                        "Sucuri": ["Sucuri", "sucuri", "x-sucuri"],
                        "Imperva": ["Incapsula", "imperva", "x-iinfo"],
                    }
                    detected = []
                    for waf_name, sigs in waf_signatures.items():
                        for sig in sigs:
                            if sig.lower() in body.lower():
                                detected.append(waf_name)
                                break
                    if detected:
                        results.append(PluginResult(
                            vulnerable=False, target=target, port=p,
                            cvss_score=0, severity="Info",
                            description=f"WAF detected: {', '.join(set(detected))} on port {p}",
                            solution="",
                            evidence=f"WAF signatures found via path '{path}': {', '.join(set(detected))}",
                            references=[]
                        ))
                        break
                except Exception:
                    continue
            else:
                results.append(PluginResult(
                    vulnerable=False, target=target, port=p,
                    cvss_score=0, severity="Info",
                    description=f"No WAF detected on port {p}",
                    solution="", evidence="", references=[]
                ))
        return results
