"""cmb-init - one command from `pip install` to a configured, agent-connected setup.

Closes the biggest first-run gap: with no configuration, an installed build puts its
database in the platform user-data directory, where most people never think to look.
This command instead writes a project-local `.env` with an explicit absolute DB path
(and optional API token), then prints exact MCP snippets to paste into Claude Code /
Cursor / Cline / Zed.

    cmb-init                 # write ./.env (kept if it exists), print next steps
    cmb-init --db ~/mem.db   # choose the database location
    cmb-init --token         # also generate a bearer token for the HTTP APIs
    cmb-init --force         # overwrite an existing .env
    cmb-init --check         # doctor: verify install, extras, DB writability

Non-interactive by design (no prompts): safe in scripts, CI, and agent shells.
"""
from __future__ import annotations

import argparse
import json
import os
import secrets
import sqlite3
import sys
import tempfile
from pathlib import Path


def _ok(label: str, detail: str = "") -> None:
    print(f"  [ok]      {label}" + (f" - {detail}" if detail else ""))


def _miss(label: str, detail: str = "") -> None:
    print(f"  [--]      {label}" + (f" - {detail}" if detail else ""))


def _fail(label: str, detail: str = "") -> None:
    print(f"  [FAIL]    {label}" + (f" - {detail}" if detail else ""))


def _try_import(name: str):
    try:
        return __import__(name)
    except Exception:
        return None


def cmd_check() -> int:
    """Doctor: report what's installed and whether the configured DB is usable."""
    failures = 0
    print(f"cmb doctor - python {sys.version.split()[0]}")

    if _try_import("numpy") is None:
        _fail("numpy (required core)", "pip install numpy")
        failures += 1
    else:
        _ok("numpy (required core)")

    for mod, label, hint in [
        ("mcp", "MCP server extra", 'pip install "cmb[mcp]"'),
        ("fastapi", "REST/Inspector extra", 'pip install "cmb[server]"'),
        ("sentence_transformers", "real embeddings",
         "optional - deterministic offline embedder is the fallback"),
        ("tree_sitter", "AST code indexing",
         "optional - regex code indexer is the fallback"),
    ]:
        available = _try_import(mod) is not None
        (_ok if available else _miss)(label, "" if available else hint)

    from cmb.config import settings
    db = Path(settings.db_path).expanduser()
    try:
        db.parent.mkdir(parents=True, exist_ok=True)
        conn = sqlite3.connect(str(db))
        conn.execute("PRAGMA user_version")
        conn.close()
        _ok("database writable", str(db))
    except Exception as exc:
        _fail("database writable", f"{db}: {exc}")
        failures += 1

    _ok("local core", "single-user features available without a hosted subscription")
    try:
        from cmb.cloud_session import configured
        if configured(require_compute=False):
            _ok("CMB Cloud", "installation connected")
        else:
            _miss("CMB Cloud", "not connected (optional for the local core)")
    except Exception:
        _miss("CMB Cloud", "saved session unavailable; reconnect if needed")

    print("all good" if failures == 0 else f"{failures} problem(s) found")
    return 0 if failures == 0 else 1


def _env_content(db_path: Path, token: str) -> str:
    lines = [
        "# CMB - generated by cmb-init. Full reference: .env.example",
        f"CMB_DB_PATH={db_path}",
    ]
    if token:
        lines += [
            "# Bearer token required by the REST server & Inspector APIs:",
            f"CMB_API_TOKEN={token}",
        ]
    lines += [
        "# Pro and Team are hosted. Connect through the CMB Cloud account portal;",
        "# never paste access or refresh credentials into a repository .env file.",
        "# CMB_CLOUD_CONTROL_URL=https://control.example.com",
        "# CMB_CLOUD_COMPUTE_URL=https://compute.example.com",
    ]
    return "\n".join(lines) + "\n"


def _write_env(path: Path, content: str) -> None:
    """Atomically replace *path* through a private temporary file.

    The file can contain an API bearer token, so it must not spend even a short window
    with the process umask's default group/world-readable permissions.
    """
    fd, temporary = tempfile.mkstemp(prefix=".%s." % path.name, suffix=".tmp",
                                     dir=str(path.parent))
    try:
        os.chmod(temporary, 0o600)
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
            fd = -1
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    except BaseException:
        if fd >= 0:
            os.close(fd)
        try:
            Path(temporary).unlink()
        except FileNotFoundError:
            pass
        raise


def _existing_db_path(env_file: Path, fallback: Path) -> Path:
    """Read the simple CMB_DB_PATH assignment emitted by this command."""
    try:
        lines = env_file.read_text(encoding="utf-8").splitlines()
    except (OSError, UnicodeError):
        return fallback
    for line in lines:
        key, separator, value = line.partition("=")
        if separator and key.strip() == "CMB_DB_PATH":
            raw = value.strip().strip("\"'")
            if raw:
                configured = Path(raw).expanduser()
                return (configured if configured.is_absolute()
                        else (env_file.parent / configured).resolve())
    return fallback


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(prog="cmb-init", description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--db", default="cmb.db",
                    help="database file (default: ./cmb.db)")
    ap.add_argument("--token", action="store_true",
                    help="generate an CMB_API_TOKEN for the HTTP APIs")
    ap.add_argument("--force", action="store_true", help="overwrite an existing .env")
    ap.add_argument("--check", action="store_true",
                    help="doctor mode: verify the installation instead of writing .env")
    args = ap.parse_args(argv)

    if args.check:
        return cmd_check()

    db_path = Path(args.db).expanduser().resolve()
    env_file = Path.cwd() / ".env"
    token = secrets.token_urlsafe(24) if args.token else ""

    if env_file.exists() and not args.force:
        print(f".env already exists at {env_file} - kept (use --force to overwrite).")
        db_path = _existing_db_path(env_file, db_path)
    else:
        _write_env(env_file, _env_content(db_path, token))
        print(f"wrote {env_file}")
        print(f"  database -> {db_path}")
        if token:
            print("  api token -> generated (in .env; send as 'Authorization: Bearer ...')")

    snippet = {"mcpServers": {"cmb": {
        "command": "cmb-mcp",
        "env": {"CMB_DB_PATH": str(db_path)},
    }}}
    print("\nConnect your agent - Claude Code:")
    print(f'  claude mcp add cmb --env CMB_DB_PATH="{db_path}"'
          " -- cmb-mcp")
    print("\nCursor / Cline / Zed / Windsurf (mcp config):")
    print(json.dumps(snippet, indent=2))
    print("\nNext steps:")
    print("  cmb-dashboard      # product UI on http://127.0.0.1:8700")
    print("  cmb-init --check   # verify the install")
    print("  Free forever at the core - start the 3-day Pro trial or subscribe at "
          "https://api.cmb.thedailyartcult.lol/account?plan=pro&interval=monthly#billing")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
