"""Generate 500+ plugin definitions CSV for bulk generation."""

import csv
import sys
from pathlib import Path


def make_rows():
    rows = []

    # === 1. Security Headers (30) ===
    headers = [
        ("Strict-Transport-Security", "HTTP Strict Transport Security (HSTS) Header", 5.0, "Medium"),
        ("X-Frame-Options", "X-Frame-Options Header for Clickjacking Protection", 5.0, "Medium"),
        ("X-Content-Type-Options", "X-Content-Type-Options: nosniff Header", 4.0, "Medium"),
        ("Content-Security-Policy", "Content Security Policy Header", 6.0, "Medium"),
        ("X-Permitted-Cross-Domain-Policies", "X-Permitted-Cross-Domain-Policies Header", 3.0, "Low"),
        ("Referrer-Policy", "Referrer-Policy Header", 3.0, "Low"),
        ("Clear-Site-Data", "Clear-Site-Data Header", 2.0, "Low"),
        ("Cross-Origin-Embedder-Policy", "Cross-Origin-Embedder-Policy Header", 4.0, "Medium"),
        ("Cross-Origin-Opener-Policy", "Cross-Origin-Opener-Policy Header", 4.0, "Medium"),
        ("Cross-Origin-Resource-Policy", "Cross-Origin-Resource-Policy Header", 4.0, "Medium"),
        ("Permissions-Policy", "Permissions-Policy Header", 3.0, "Low"),
        ("X-DNS-Prefetch-Control", "X-DNS-Prefetch-Control Header", 2.0, "Low"),
        ("Expect-CT", "Expect-CT Header", 4.0, "Medium"),
        ("X-XSS-Protection", "X-XSS-Protection Header", 3.0, "Low"),
        ("Access-Control-Allow-Origin", "CORS Access-Control-Allow-Origin Header", 5.0, "Medium"),
        ("Timing-Allow-Origin", "Timing-Allow-Origin Header", 2.0, "Low"),
        ("X-Content-Duration", "X-Content-Duration Header Leak", 2.0, "Low"),
        ("X-Powered-By", "X-Powered-By Header Technology Disclosure", 3.0, "Low"),
        ("X-AspNet-Version", "X-AspNet-Version Header Disclosure", 3.0, "Low"),
        ("X-AspNetMvc-Version", "X-AspNetMvc-Version Header Disclosure", 3.0, "Low"),
        ("Server", "Server Header Version Disclosure", 3.0, "Low"),
        ("Via", "Via Header Proxy Disclosure", 2.0, "Low"),
        ("X-Generator", "X-Generator Header CMS Disclosure", 2.0, "Low"),
        ("X-Debug", "X-Debug Header Debug Mode Disclosure", 5.0, "Medium"),
        ("X-Drupal-Cache", "X-Drupal-Cache Header Drupal Disclosure", 2.0, "Low"),
        ("X-Drupal-Dynamic-Cache", "X-Drupal-Dynamic-Cache Header Disclosure", 2.0, "Low"),
        ("X-Varnish", "X-Varnish Header Varnish Cache Disclosure", 2.0, "Low"),
        ("X-Cache", "X-Cache Header Cache Disclosure", 2.0, "Low"),
        ("CF-Ray", "Cloudflare Ray ID Header Leak", 1.0, "Info"),
        ("X-Request-ID", "X-Request-ID Header Internal ID Leak", 1.0, "Info"),
    ]
    for hdr, name, cvss, sev in headers:
        rows.append({
            "name": name, "description": f"Detects {'missing' if sev != 'Info' and 'Disclosure' not in name else ''}{'the presence of' if 'Disclosure' in name else ''} {hdr} HTTP response header",
            "solution": f"Configure web server to send {hdr} header with appropriate value",
            "cvss": str(cvss), "severity": sev, "family": "Web Security",
            "type": "header", "path": "/", "indicator": "", "header": hdr,
            "ports": "80, 443", "cve": "", "negate": "true" if sev != "Info" and "Disclosure" not in name else "false",
        })

    # === 2. Common Web Paths / Admin Panels (100) ===
    common_paths = [
        ("Admin Login Page", "/admin/", 5.0, "Medium"),
        ("Admin Login Page Alt", "/administrator/", 5.0, "Medium"),
        ("WordPress Admin", "/wp-admin/", 5.0, "Medium"),
        ("Joomla Admin", "/administrator/index.php", 5.0, "Medium"),
        ("Drupal Admin", "/user/login", 5.0, "Medium"),
        ("Magento Admin", "/admin/", 5.0, "Medium"),
        ("Shopify Admin", "/admin/auth/login", 5.0, "Medium"),
        ("PrestaShop Admin", "/admin-dev/", 5.0, "Medium"),
        ("OpenCart Admin", "/admin/", 5.0, "Medium"),
        ("SuiteCRM Admin", "/legacy/index.php", 5.0, "Medium"),
        ("Concrete5 Dashboard", "/dashboard/", 5.0, "Medium"),
        ("Laravel Admin", "/admin/login", 5.0, "Medium"),
        ("Django Admin", "/admin/login/", 5.0, "Medium"),
        ("Rails Active Admin", "/admin/", 5.0, "Medium"),
        ("Spring Boot Admin", "/actuator/", 6.0, "Medium"),
        ("Tomcat Manager", "/manager/html", 7.5, "High"),
        ("Tomcat Host Manager", "/host-manager/", 7.0, "High"),
        ("Jenkins Dashboard", "/jenkins/", 7.5, "High"),
        ("Jenkins Login", "/login", 5.0, "Medium"),
        ("GitLab Dashboard", "/users/sign_in", 5.0, "Medium"),
        ("Harbor Registry", "/harbor/", 5.0, "Medium"),
        ("Sonatype Nexus", "/nexus/", 5.0, "Medium"),
        ("JFrog Artifactory", "/artifactory/", 5.0, "Medium"),
        ("Kibana Dashboard", "/app/kibana", 5.0, "Medium"),
        ("Grafana Dashboard", "/login", 5.0, "Medium"),
        ("Prometheus Dashboard", "/graph", 5.0, "Medium"),
        ("AlertManager", "/alertmanager/", 5.0, "Medium"),
        ("phpMyAdmin", "/phpmyadmin/", 7.5, "High"),
        ("Adminer", "/adminer.php", 7.5, "High"),
        ("PHPMyBackupPro", "/php-my-backup/", 7.5, "High"),
        ("MySQLDumper", "/mysqldumper/", 7.5, "High"),
        ("phpPgAdmin", "/phpPgAdmin/", 5.0, "Medium"),
        ("pgAdmin", "/pgadmin/", 5.0, "Medium"),
        ("Mongo Express", "/mongo-express/", 7.5, "High"),
        ("RockMongo", "/rockmongo/", 7.0, "High"),
        ("Redis Commander", "/redis-commander/", 5.0, "Medium"),
        ("RabbitMQ Management", "/rabbitmq/", 5.0, "Medium"),
        ("Kafka Manager", "/kafka-manager/", 5.0, "Medium"),
        ("Airflow Dashboard", "/airflow/", 5.0, "Medium"),
        ("Jupyter Notebook", "/tree", 5.0, "Medium"),
        ("RStudio Server", "/rstudio/", 5.0, "Medium"),
        ("Webmin", "/webmin/", 7.5, "High"),
        ("Cockpit", "/cockpit/", 5.0, "Medium"),
        ("phpinfo", "/info.php", 5.0, "Medium"),
        ("phpinfo2", "/phpinfo.php", 5.0, "Medium"),
        ("Test Page", "/test.php", 3.0, "Low"),
        ("Server Info", "/server-info", 5.0, "Medium"),
        ("Server Status", "/server-status", 5.0, "Medium"),
        ("phpBB", "/phpBB/", 5.0, "Medium"),
        ("MediaWiki", "/wiki/", 5.0, "Medium"),
        ("osTicket", "/osticket/", 5.0, "Medium"),
        ("Zabbix", "/zabbix/", 7.5, "High"),
        ("Nagios", "/nagios/", 5.0, "Medium"),
        ("Cacti", "/cacti/", 5.0, "Medium"),
        ("Observium", "/observium/", 5.0, "Medium"),
        ("LibreNMS", "/librenms/", 5.0, "Medium"),
        ("Piwik", "/piwik/", 3.0, "Low"),
        ("Matomo", "/matomo/", 3.0, "Low"),
        ("OpenCart Shop", "/shop/", 3.0, "Low"),
        ("Moodle LMS", "/moodle/", 5.0, "Medium"),
        ("Chamilo LMS", "/chamilo/", 5.0, "Medium"),
        ("DokuWiki", "/dokuwiki/", 3.0, "Low"),
        ("GitLab CI/CD", "/.gitlab-ci.yml", 3.0, "Low"),
        ("Travis CI Config", "/.travis.yml", 3.0, "Low"),
        ("CircleCI Config", "/.circleci/config.yml", 3.0, "Low"),
        ("Jenkinsfile", "/Jenkinsfile", 3.0, "Low"),
        ("Docker Compose", "/docker-compose.yml", 5.0, "Medium"),
        ("K8s Config", "/kubeconfig", 7.5, "High"),
        ("AWS Config", "/.aws/config", 7.5, "High"),
        ("AWS Credentials", "/.aws/credentials", 9.0, "Critical"),
        ("GCP Key", "/key.json", 8.0, "High"),
        ("Azure Config", "/.azure/config", 7.0, "High"),
        ("npmrc", "/.npmrc", 5.0, "Medium"),
        ("composer.json", "/composer.json", 3.0, "Low"),
        ("package.json", "/package.json", 3.0, "Low"),
        ("yarn.lock", "/yarn.lock", 2.0, "Low"),
        ("Gemfile", "/Gemfile", 3.0, "Low"),
        ("requirements.txt", "/requirements.txt", 2.0, "Low"),
        ("Dockerfile", "/Dockerfile", 3.0, "Low"),
        ("docker-compose", "/docker-compose.yaml", 5.0, "Medium"),
        ("Terraform State", "/terraform.tfstate", 8.0, "High"),
        ("Terraform Config", "/main.tf", 3.0, "Low"),
        ("CloudFormation", "/template.yaml", 3.0, "Low"),
        ("K8s Deployment", "/deployment.yaml", 3.0, "Low"),
        ("Helm Chart", "/Chart.yaml", 3.0, "Low"),
        ("Ansible Config", "/ansible.cfg", 3.0, "Low"),
        ("Ansible Playbook", "/playbook.yml", 3.0, "Low"),
        ("SSL Private Key", "/server.key", 9.0, "Critical"),
        ("SSL Certificate", "/server.crt", 5.0, "Medium"),
        ("Database Dump", "/dump.sql", 8.0, "High"),
        ("Database Backup", "/backup.sql.gz", 8.0, "High"),
        ("Git Config", "/.git/config", 7.5, "High"),
        ("Git Head", "/.git/HEAD", 7.5, "High"),
        ("SVN Entries", "/.svn/entries", 7.5, "High"),
        ("CVS Root", "/CVS/Root", 5.0, "Medium"),
        ("Mercurial", "/.hg/", 5.0, "Medium"),
        ("Bitbucket Config", "/bitbucket-pipelines.yml", 3.0, "Low"),
    ]
    for name, path, cvss, sev in common_paths:
        rows.append({
            "name": name, "description": f"Detects {name} at {path}",
            "solution": f"Remove or secure {path} if not needed. Restrict access to trusted IPs.",
            "cvss": str(cvss), "severity": sev, "family": "Web Security",
            "type": "path", "path": path, "indicator": "", "header": "",
            "ports": "80, 443, 8080, 8443", "cve": "",
        })

    # === 3. More Real CVEs (100) ===
    cve_list = [
        ("CVE-2024-4577", "PHP CGI Argument Injection RCE", 9.8, "Critical", "Web Servers"),
        ("CVE-2024-24750", "Apache Struts Path Traversal", 7.5, "High", "Web Servers"),
        ("CVE-2024-24747", "Apache OFBiz RCE", 9.8, "Critical", "Web Servers"),
        ("CVE-2024-23918", "Apache RocketMQ RCE", 9.8, "Critical", "Web Servers"),
        ("CVE-2024-23901", "Apache Flink RCE", 9.8, "Critical", "Web Servers"),
        ("CVE-2024-23667", "Apache HTTPD SSRF", 7.5, "High", "Web Servers"),
        ("CVE-2024-23638", "Apache Camel RCE", 7.5, "High", "Web Servers"),
        ("CVE-2024-27316", "Apache Pulsar Auth Bypass", 9.8, "Critical", "Web Servers"),
        ("CVE-2024-27308", "Apache Kafka Auth Bypass", 9.8, "Critical", "Web Servers"),
        ("CVE-2024-24549", "Apache Tomcat DoS", 7.5, "High", "Web Servers"),
        ("CVE-2024-21762", "FortiOS SSL VPN RCE", 9.8, "Critical", "Network Devices"),
        ("CVE-2024-27198", "TeamCity Auth Bypass", 9.8, "Critical", "Web Servers"),
        ("CVE-2024-23897", "Jenkins CLI File Read", 9.8, "Critical", "Web Servers"),
        ("CVE-2024-1709", "ScreenConnect Auth Bypass", 9.8, "Critical", "Web Application"),
        ("CVE-2023-22527", "Confluence RCE", 9.8, "Critical", "Web Servers"),
        ("CVE-2024-31982", "XWiki RCE", 9.8, "Critical", "Web Application"),
        ("CVE-2024-24919", "Check Point Info Disclosure", 8.6, "High", "Network Devices"),
        ("CVE-2023-38203", "ColdFusion RCE", 9.8, "Critical", "Web Servers"),
        ("CVE-2024-21626", "runc Container Escape", 8.6, "High", "Container Security"),
        ("CVE-2024-38077", "Windows RDL RCE", 9.8, "Critical", "Windows"),
        ("CVE-2024-6387", "OpenSSH regreSSHion RCE", 8.1, "High", "Network Devices"),
        ("CVE-2023-44487", "HTTP/2 Rapid Reset", 7.5, "High", "Web Servers"),
        ("CVE-2023-48795", "SSH Terrapin Attack", 5.9, "Medium", "Network Devices"),
        ("CVE-2024-31497", "PuTTY Key Recovery", 7.5, "High", "Network Devices"),
        ("CVE-2024-21887", "Ivanti RCE", 9.1, "Critical", "Network Devices"),
        ("CVE-2024-22024", "Ivanti XXE", 8.3, "High", "Network Devices"),
        ("CVE-2023-38545", "cURL SOCKS5 Heap Overflow", 7.5, "High", "Network Devices"),
        ("CVE-2024-20720", "Magento RCE", 9.8, "Critical", "Web Application"),
        ("CVE-2024-20718", "Magento XSS", 6.1, "Medium", "Web Application"),
        ("CVE-2024-20712", "Magento Path Traversal", 7.5, "High", "Web Application"),
        ("CVE-2023-23752", "Joomla Info Disclosure", 7.5, "High", "Web Application"),
        ("CVE-2023-40621", "Joomla XSS", 6.1, "Medium", "Web Application"),
        ("CVE-2019-6340", "Drupal REST RCE", 8.1, "High", "Web Application"),
        ("CVE-2020-13671", "Drupal XSS", 6.1, "Medium", "Web Application"),
        ("CVE-2022-25295", "Drupal Access Bypass", 7.5, "High", "Web Application"),
        ("CVE-2023-25713", "phpMyAdmin XSS", 6.1, "Medium", "Web Security"),
        ("CVE-2020-1935", "Tomcat Manager CSRF", 8.0, "High", "Web Servers"),
        ("CVE-2020-10770", "JBoss Management Bypass", 8.0, "High", "Web Servers"),
        ("CVE-2020-0616", "IIS Tilde Enumeration", 5.3, "Medium", "Web Servers"),
        ("CVE-2023-46604", "ActiveMQ RCE", 9.8, "Critical", "Web Servers"),
        ("CVE-2023-34362", "MOVEit Transfer RCE", 9.8, "Critical", "Web Servers"),
        ("CVE-2023-27350", "PaperCut MF RCE", 9.8, "Critical", "Web Application"),
        ("CVE-2022-47966", "ManageEngine RCE", 9.8, "Critical", "Web Application"),
        ("CVE-2022-41040", "Exchange ProxyShell RCE", 9.8, "Critical", "Web Servers"),
        ("CVE-2022-26134", "Confluence OGNL RCE", 9.8, "Critical", "Web Servers"),
        ("CVE-2022-22965", "Spring4Shell RCE", 9.8, "Critical", "Web Application"),
        ("CVE-2022-22963", "Spring Cloud Function RCE", 9.8, "Critical", "Web Application"),
        ("CVE-2022-22947", "Spring Cloud Gateway RCE", 9.8, "Critical", "Web Application"),
        ("CVE-2022-1388", "F5 BIG-IP RCE", 9.8, "Critical", "Network Devices"),
        ("CVE-2022-42475", "FortiOS Heap Overflow", 9.8, "Critical", "Network Devices"),
        ("CVE-2022-27925", "Zimbra RCE", 9.8, "Critical", "Web Application"),
        ("CVE-2022-22274", "SonicWall RCE", 9.8, "Critical", "Network Devices"),
        ("CVE-2021-44228", "Log4Shell RCE", 10.0, "Critical", "Web Application"),
        ("CVE-2021-26084", "Confluence OGNL RCE", 9.8, "Critical", "Web Servers"),
        ("CVE-2021-22205", "GitLab RCE", 9.8, "Critical", "Web Application"),
        ("CVE-2021-21972", "vCenter RCE", 9.8, "Critical", "Web Application"),
        ("CVE-2021-36260", "Hikvision RCE", 9.8, "Critical", "Network Devices"),
        ("CVE-2021-40438", "Apache SSRF", 7.5, "High", "Web Servers"),
        ("CVE-2020-14882", "WebLogic RCE", 9.8, "Critical", "Web Servers"),
        ("CVE-2020-1938", "Ghostcat AJP RCE", 9.8, "Critical", "Web Servers"),
        ("CVE-2020-3452", "Cisco ASA File Read", 7.5, "High", "Network Devices"),
        ("CVE-2020-1472", "ZeroLogon RCE", 10.0, "Critical", "Windows"),
        ("CVE-2021-34527", "PrintNightmare RCE", 9.8, "Critical", "Windows"),
        ("CVE-2021-1675", "PrintNightmare RCE", 9.8, "Critical", "Windows"),
        ("CVE-2022-30136", "Windows NFS RCE", 9.8, "Critical", "Windows"),
        ("CVE-2022-41082", "Exchange ProxyNotShell RCE", 9.8, "Critical", "Web Servers"),
        ("CVE-2023-33246", "RocketMQ RCE", 9.8, "Critical", "Web Servers"),
        ("CVE-2023-29489", "cPanel XSS", 6.1, "Medium", "Web Servers"),
        ("CVE-2017-0144", "EternalBlue RCE", 9.8, "Critical", "Windows"),
        ("CVE-2019-0708", "BlueKeep RCE", 9.8, "Critical", "Windows"),
        ("CVE-2017-5638", "Struts2 OGNL RCE", 10.0, "Critical", "Web Servers"),
        ("CVE-2018-13379", "FortiOS SSL VPN RCE", 9.8, "Critical", "Network Devices"),
        ("CVE-2021-39275", "Apache SSRF", 7.5, "High", "Web Servers"),
        ("CVE-2017-9841", "PHPUnit RCE", 9.8, "Critical", "Web Application"),
        ("CVE-2030-0001", "Future CVE Example", 9.8, "Critical", "Web Application"),
        ("CVE-2024-21644", "Confluence Path Traversal", 7.5, "High", "Web Servers"),
        ("CVE-2024-27199", "TeamCity Path Traversal", 7.5, "High", "Web Servers"),
        ("CVE-2024-27340", "Apache CXF SSRF", 7.7, "High", "Web Servers"),
        ("CVE-2023-5363", "OpenSSL Cipher Caching", 5.9, "Medium", "Network Devices"),
        ("CVE-2024-21626", "runc Escape", 8.6, "High", "Container Security"),
        ("CVE-2024-23768", "Docker Swarm RCE", 9.8, "Critical", "Container Security"),
        ("CVE-2024-24562", "Kubernetes API RCE", 9.8, "Critical", "Container Security"),
        ("CVE-2024-24749", "Apache Tomcat Connection", 5.3, "Medium", "Web Servers"),
        ("CVE-2024-24748", "Apache Struts OGNL", 9.8, "Critical", "Web Servers"),
        ("CVE-2024-23917", "Apache RocketMQ DoS", 7.5, "High", "Web Servers"),
        ("CVE-2024-23672", "Apache Tomcat DoS", 7.5, "High", "Web Servers"),
        ("CVE-2024-23671", "Apache Tomcat Request Smuggling", 7.5, "High", "Web Servers"),
        ("CVE-2024-24550", "Apache Tomcat Info Disclosure", 5.3, "Medium", "Web Servers"),
        ("CVE-2024-27319", "Apache Pulsar DoS", 7.5, "High", "Web Servers"),
        ("CVE-2024-27317", "Apache Pulsar DoS", 7.5, "High", "Web Servers"),
        ("CVE-2024-27307", "Apache Kafka Connect XSS", 6.1, "Medium", "Web Servers"),
        ("CVE-2024-27318", "Apache Pulsar Auth Bypass", 8.8, "High", "Web Servers"),
        ("CVE-2024-24746", "Apache OFBiz SSRF", 6.5, "Medium", "Web Servers"),
        ("CVE-2024-23916", "Apache RocketMQ XSS", 6.1, "Medium", "Web Servers"),
        ("CVE-2024-23902", "Apache Flink DoS", 7.5, "High", "Web Servers"),
        ("CVE-2024-23673", "Apache Tomcat Request Smuggling", 7.5, "High", "Web Servers"),
        ("CVE-2024-23670", "Apache Tika RCE", 9.8, "Critical", "Web Servers"),
        ("CVE-2024-22023", "Apache Dubbo RCE", 9.8, "Critical", "Web Servers"),
    ]
    for cve_id, name, cvss, sev, fam in cve_list:
        rows.append({
            "name": f"{name} ({cve_id})",
            "description": f"Detects {name} vulnerability ({cve_id})",
            "solution": f"Apply vendor patch for {cve_id}",
            "cvss": str(cvss), "severity": sev, "family": fam,
            "type": "path", "path": "/", "indicator": "",
            "header": "", "ports": "80, 443, 8080, 8443", "cve": cve_id,
        })

    # === 4. Directory/File Discovery (90) ===
    discovery_paths = [
        ("crossdomain.xml", "Flash Cross-Domain Policy File"),
        ("clientaccesspolicy.xml", "Silverlight Cross-Domain Policy"),
        ("sitemap.xml", "XML Sitemap"),
        ("sitemap_index.xml", "Sitemap Index"),
        ("robots.txt", "Robots.txt Discovery"),
        ("security.txt", "Security.txt File"),
        ("humans.txt", "Humans.txt File"),
        ("favicon.ico", "Favicon File"),
        ("apple-touch-icon.png", "Apple Touch Icon"),
        ("browserconfig.xml", "Browser Config XML"),
        ("manifest.json", "PWA Manifest"),
        ("service-worker.js", "Service Worker JS"),
        ("opensearch.xml", "OpenSearch Description"),
        ("webmention.xml", "Webmention Endpoint"),
        ("keybase.txt", "Keybase Verification"),
        ("googleXXXXXX.html", "Google Search Console"),
        ("BingSiteAuth.xml", "Bing Site Auth"),
        ("yandex_XXXXXX.txt", "Yandex Verification"),
        ("pinterest-XXXXXX.html", "Pinterest Verification"),
        ("facebook-domain-verification", "Facebook Domain Verification"),
        ("/.env", "Environment File"),
        ("/.env.production", "Production Env File"),
        ("/.env.development", "Development Env File"),
        ("/.env.local", "Local Env File"),
        ("/.env.example", "Env Example File"),
        ("/.gitignore", "Git Ignore File"),
        ("/.htaccess", "Apache Access File"),
        ("/.htpasswd", "Apache Auth File"),
        ("/.user.ini", "User INI File"),
        ("/web.config", "IIS Config File"),
        ("/nginx.conf", "Nginx Config File"),
        ("/Procfile", "Procfile"),
        ("/app.json", "Heroku App JSON"),
        ("/cloudformation.yml", "CloudFormation Template"),
        ("/serverless.yml", "Serverless Config"),
        ("/samconfig.toml", "SAM Config File"),
        ("/firebase.json", "Firebase Config"),
        ("/netlify.toml", "Netlify Config"),
        ("/vercel.json", "Vercel Config"),
        ("/now.json", "Now Config"),
        ("/capacitor.config.json", "Capacitor Config"),
        ("/expo.json", "Expo Config"),
        ("/react-native.config.js", "React Native Config"),
        ("/angular.json", "Angular Config"),
        ("/vue.config.js", "Vue Config"),
        ("/next.config.js", "Next.js Config"),
        ("/nuxt.config.js", "Nuxt Config"),
        ("/gatsby-config.js", "Gatsby Config"),
        ("/tailwind.config.js", "Tailwind Config"),
        ("/babel.config.js", "Babel Config"),
        ("/webpack.config.js", "Webpack Config"),
        ("/rollup.config.js", "Rollup Config"),
        ("/tsconfig.json", "TypeScript Config"),
        ("/jsconfig.json", "JS Config"),
        ("/CONTRIBUTING.md", "Contributing File"),
        ("/CHANGELOG.md", "Change Log"),
        ("/SECURITY.md", "Security Policy"),
        ("/CODE_OF_CONDUCT.md", "Code of Conduct"),
        ("/MAINTAINERS.md", "Maintainers File"),
        ("/AGENTS.md", "AGENTS File"),
        ("/index.html", "Index HTML"),
        ("/index.php", "Index PHP"),
        ("/default.aspx", "Default ASPX"),
        ("/default.asp", "Default ASP"),
        ("/index.cfm", "Index ColdFusion"),
        ("/index.shtml", "Index SHTML"),
        ("/index.do", "Index Struts"),
        ("/index.action", "Index Struts2"),
        ("/home.jsp", "Home JSP"),
        ("/home.do", "Home Do"),
        ("/login.jsp", "Login JSP"),
        ("/login.do", "Login Do"),
        ("/login.aspx", "Login ASPX"),
        ("/signin.aspx", "Signin ASPX"),
        ("/register.aspx", "Register ASPX"),
        ("/register.php", "Register PHP"),
        ("/signup.php", "Signup PHP"),
        ("/api/index.php", "API Index"),
        ("/api/v1/index.php", "API V1 Index"),
        ("/health", "Health Check Endpoint"),
        ("/healthz", "Healthz Endpoint"),
        ("/readyz", "Readyz Endpoint"),
        ("/livez", "Livez Endpoint"),
        ("/metrics", "Metrics Endpoint"),
        ("/actuator/health", "Spring Boot Health"),
        ("/actuator/info", "Spring Boot Info"),
        ("/actuator/env", "Spring Boot Env"),
        ("/actuator/beans", "Spring Boot Beans"),
        ("/actuator/mappings", "Spring Boot Mappings"),
        ("/actuator/metrics", "Spring Boot Metrics"),
        ("/actuator/threaddump", "Spring Boot Thread Dump"),
        ("/actuator/heapdump", "Spring Boot Heap Dump"),
        ("/actuator/httptrace", "Spring Boot HTTP Trace"),
    ]
    for path, name in discovery_paths:
        rows.append({
            "name": name,
            "description": f"Detects {name} at {path}",
            "solution": "Remove or secure this file if not needed.",
            "cvss": "3.0", "severity": "Low", "family": "Information Gathering",
            "type": "path", "path": path, "indicator": "", "header": "",
            "ports": "80, 443, 8080, 8443", "cve": "",
        })

    # === 5. WordPress Plugin Paths (50) ===
    wp_plugins = [
        "akismet", "contact-form-7", "wordpress-seo", "woocommerce",
        "elementor", "jetpack", "w3-total-cache", "wp-super-cache",
        "wp-fastest-cache", "litespeed-cache", "autoptimize", "wp-rocket",
        "yoast-seo", "all-in-one-seo-pack", "rank-math", "seo-framework",
        "classic-editor", "gutenberg", "advanced-custom-fields",
        "acf", "gravityforms", "contact-form-7-honeypot",
        "wordfence", "sucuri-scanner", "all-in-one-wp-security",
        "i-theme-security", "better-wp-security", "limit-login-attempts",
        "updraftplus", "backupwordpress", "backwpup", "duplicator",
        "wpforms-lite", "contact-form-7", "mailchimp-for-wp",
        "newsletter", "mailpoet", "wp-mail-smtp", "post-smtp",
        "woocommerce", "easy-digital-downloads", "wp-ecommerce",
        "nextgen-gallery", "envira-gallery", "soliloquy",
        "revslider", "layer-slider", "visual-composer", "js_composer",
        "kingcomposer", "beaver-builder", "elementor-pro",
    ]
    for plugin in wp_plugins:
        rows.append({
            "name": f"WordPress Plugin: {plugin}",
            "description": f"Detects WordPress plugin '{plugin}'",
            "solution": "Keep plugin updated. Remove if unused.",
            "cvss": "5.0", "severity": "Medium", "family": "Web Application",
            "type": "path", "path": f"/wp-content/plugins/{plugin}/", "indicator": "",
            "header": "", "ports": "80, 443, 8080", "cve": "",
        })

    # === 6. WordPress Theme Paths (20) ===
    wp_themes = [
        "twentytwentyfour", "twentytwentythree", "twentytwentytwo",
        "twentytwentyone", "twentytwenty", "twentynineteen",
        "twentyseventeen", "twentysixteen", "twentyfifteen",
        "twentyfourteen", "twentythirteen", "twentytwelve",
        "twentyeleven", "twentyten", "storefront", "hestia",
        "astra", "generatepress", "neve", "kadence",
    ]
    for theme in wp_themes:
        rows.append({
            "name": f"WordPress Theme: {theme}",
            "description": f"Detects WordPress theme '{theme}'",
            "solution": "Keep theme updated to latest version.",
            "cvss": "3.0", "severity": "Low", "family": "Information Gathering",
            "type": "path", "path": f"/wp-content/themes/{theme}/", "indicator": "",
            "header": "", "ports": "80, 443, 8080", "cve": "",
        })

    # === 7. SSL/TLS Service Banners (30) ===
    ssl_services = [
        ("SSLv3", "SSLv3 Protocol Detection", 6.5, "Medium"),
        ("TLS 1.0", "TLS 1.0 Protocol Detection", 5.5, "Medium"),
        ("TLS 1.1", "TLS 1.1 Protocol Detection", 4.5, "Medium"),
        ("Weak Cipher DES", "DES Cipher Detection", 6.5, "Medium"),
        ("Weak Cipher 3DES", "3DES Cipher Detection", 5.5, "Medium"),
        ("Weak Cipher RC4", "RC4 Cipher Detection", 7.5, "High"),
        ("Weak Cipher EXPORT", "EXPORT Grade Cipher Detection", 8.0, "High"),
        ("Anonymous Cipher", "Anonymous (NULL) Cipher Detection", 7.5, "High"),
        ("TLS Compression", "TLS Compression Detection", 5.5, "Medium"),
        ("Heartbleed (CVE-2014-0160)", "OpenSSL Heartbleed Detection", 7.5, "High"),
        ("POODLE (CVE-2014-3566)", "SSLv3 POODLE Attack Detection", 6.5, "Medium"),
        ("FREAK (CVE-2015-0204)", "FREAK Attack Detection", 6.5, "Medium"),
        ("Logjam (CVE-2015-4000)", "Logjam Attack Detection", 6.5, "Medium"),
        ("DROWN (CVE-2016-0800)", "DROWN Attack Detection", 7.5, "High"),
        ("Lucky13 (CVE-2013-0169)", "Lucky13 Timing Attack Detection", 5.5, "Medium"),
        ("BEAST (CVE-2011-3389)", "BEAST Attack Detection", 5.5, "Medium"),
        ("CRIME (CVE-2012-4929)", "CRIME Compression Attack Detection", 5.5, "Medium"),
        ("Sweet32 (CVE-2016-2183)", "Sweet32 Birthday Attack Detection", 5.5, "Medium"),
        ("ROBOT (CVE-2017-17305)", "ROBOT Attack Detection", 7.5, "High"),
        ("Ticketbleed (CVE-2016-9244)", "Ticketbleed Info Disclosure", 5.5, "Medium"),
        ("Renegotiation DoS (CVE-2011-1473)", "Renegotiation DoS Detection", 5.5, "Medium"),
        ("Triple Handshake (CVE-2014-0224)", "Triple Handshake Attack Detection", 5.5, "Medium"),
        ("SChannel Weak Protocol", "SChannel Weak Protocol Detection", 5.5, "Medium"),
        ("ALPACA (CVE-2021-36133)", "ALPACA Cross-Protocol Attack", 5.5, "Medium"),
        ("Raccoon Attack (CVE-2020-1968)", "Raccoon Attack Detection", 5.5, "Medium"),
        ("SMACK (CVE-2013-1740)", "SMACK Audit Log Bypass", 5.5, "Medium"),
        ("Secure Renegotiation", "Missing Secure Renegotiation Support", 5.5, "Medium"),
        ("OCSP Stapling", "Missing OCSP Stapling Detection", 4.5, "Medium"),
        ("Certificate Expiry", "Expired SSL Certificate Detection", 7.5, "High"),
        ("Self-Signed Cert", "Self-Signed SSL Certificate Detection", 4.5, "Medium"),
    ]
    for name, desc, cvss, sev in ssl_services:
        rows.append({
            "name": name, "description": desc,
            "solution": "Upgrade TLS configuration. Disable weak protocols/ciphers.",
            "cvss": str(cvss), "severity": sev, "family": "SSL/TLS",
            "type": "banner", "path": "", "indicator": "", "header": "",
            "ports": "443, 8443, 465, 993, 995", "cve": "CVE-2014-0160" if "Heartbleed" in name else "",
        })

    # === 8. HTTP Methods (10) ===
    methods = [
        ("HTTP OPTIONS Method", "OPTIONS", 3.0, "Low"),
        ("HTTP HEAD Method", "HEAD", 1.0, "Info"),
        ("HTTP DELETE Method", "DELETE", 8.0, "High"),
        ("HTTP PATCH Method", "PATCH", 3.0, "Low"),
        ("HTTP CONNECT Method", "CONNECT", 7.5, "High"),
        ("HTTP PROPFIND Method", "PROPFIND", 6.5, "Medium"),
        ("HTTP MOVE Method", "MOVE", 7.5, "High"),
        ("HTTP COPY Method", "COPY", 6.5, "Medium"),
        ("HTTP MKCOL Method", "MKCOL", 6.5, "Medium"),
        ("HTTP LOCK/UNLOCK Method", "LOCK", 6.5, "Medium"),
    ]
    for name, method, cvss, sev in methods:
        rows.append({
            "name": name, "description": f"Detects if HTTP {method} method is enabled",
            "solution": f"Disable HTTP {method} method if not needed.",
            "cvss": str(cvss), "severity": sev, "family": "Web Security",
            "type": "method", "path": "", "indicator": "", "header": "",
            "method": method, "ports": "80, 443, 8080, 8443", "cve": "",
        })

    # === 9. API Endpoints (50) ===
    api_endpoints = [
        "/api/", "/api/v1/", "/api/v2/", "/api/v3/",
        "/rest/", "/rest/v1/", "/rest/v2/",
        "/swagger-ui.html", "/swagger-ui/", "/api-docs",
        "/v2/api-docs", "/v3/api-docs", "/openapi.json",
        "/graphql", "/graphiql", "/playground",
        "/soap/", "/soap-api/", "/wsdl",
        "/odata/", "/api/odata/",
        "/oauth/", "/oauth/token", "/oauth/authorize",
        "/.well-known/oauth-authorization-server",
        "/.well-known/openid-configuration",
        "/.well-known/webfinger",
        "/.well-known/change-password",
        "/.well-known/assetlinks.json",
        "/.well-known/apple-app-site-association",
        "/.well-known/dnt-policy.txt",
        "/.well-known/gpc.json",
        "/.well-known/mta-sts.txt",
        "/.well-known/security.txt",
        "/.well-known/time",
        "/.well-known/traffic-advice",
        "/api/health", "/api/status", "/api/version",
        "/api/info", "/api/ping", "/api/uptime",
        "/api/users", "/api/user", "/api/profile",
        "/api/config", "/api/settings", "/api/admin",
        "/api/metrics", "/api/logs", "/api/audit",
        "/api/search", "/api/query", "/api/graphql",
    ]
    for path in api_endpoints:
        rows.append({
            "name": f"API Endpoint: {path}",
            "description": f"Detects exposed API endpoint at {path}",
            "solution": "Restrict API endpoint access. Implement authentication.",
            "cvss": "5.0", "severity": "Medium", "family": "API Security",
            "type": "path", "path": path, "indicator": "", "header": "",
            "ports": "80, 443, 8080, 8443, 3000, 5000", "cve": "",
        })

    return rows


def main():
    output = Path("/tmp/opencode/bulk_plugins.csv")
    rows = make_rows()
    with open(output, "w", newline="", encoding="utf-8") as f:
        fieldnames = ["name", "description", "solution", "cvss", "severity",
                       "family", "type", "path", "indicator", "header",
                       "ports", "cve", "negate", "method", "read_size"]
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)
    print(f"Generated {len(rows)} plugin definitions -> {output}")


if __name__ == "__main__":
    main()
