var PanteonSecurity=(function(){"use strict";var a="1.0.0",b=!1,c={honeypotsActive:!1,antiScrapingActive:!1,selfHealingActive:!1,threatsDetected:0,lastThreat:null};
var p0="WyJib3QiLCJjcmF3bGVyIiwic3BpZGVyIiwic2NyYXBlciIsImhhcnZlc3RlciIsImN1cmwiLCJ3Z2V0IiwicHl0aG9uLXJlcXVlc3RzIiwiZ28taHR0cC1jbGllbnQiLCJqYXZhLyIsInBlcmwiLCJydWJ5IiwicGhwLyIsIm5tYXAiLCJuaWt0byIsInNxbG1hcCIsIm";var p1="5lc3N1cyIsIm9wZW52YXMiLCJhY3VuZXRpeCIsImJ1cnAiLCJ3cHNjYW4iLCJkaXJidXN0ZXIiLCJmZnVmIiwiZ29idXN0ZXIiLCJmZXJveGJ1c3RlciIsIndmdXp6IiwiaGVhZGxlc3NjaHJvbWUiLCJoZWFkbGVzc2ZpcmVmb3giLCJwaGFudG9tanMiLCJwbGF5d3Jp";var p2="Z2h0IiwicHVwcGV0ZWVyIiwic2VsZW5pdW0iLCJncHRib3QiLCJjaGF0Z3B0LXVzZXIiLCJjY2JvdCIsImFudGhyb3BpYyIsImNsYXVkZWJvdCIsImdvb2dsZS1leHRlbmRlZCIsImJ5dGVzcGlkZXIiLCJvbWdpbGlib3QiLCJmYWNlYm9va2JvdCIsInBldGFsYm90Il0=";
var q0="WyIuZ2l0IiwiLmVudiIsIndwLWFkbWluIiwid3AtbG9naW4iLCJ4bWxycGMucGhwIiwiYWRtaW4iLCJiYWNrdXAiLCJj";var q1="b25maWciLCJwaHBteWFkbWluIiwic2VydmVyLXN0YXR1cyIsInNlcnZlci1pbmZvIiwiLmh0YWNjZXNzIiwiLmh0cGFz";var q2="c3dkIiwiZGVidWciLCJhcGkvdiIsInN3YWdnZXIiLCJncmFwaHFsIiwiLnNxbCIsIi5iYWsiLCIub2xkIiwiLnN3cCJd";
var r0="WyIvYWRtaW4vYmFja3VwLWRiIiwiL2FkbWluL3Jlc3RvcmUiLCIvYWRtaW4vbG9naW4iLCIvYWRtaW5lci5waHAiLCIvYWRtaW4vY29uc29sZSIsIi9hcGkvdjEvdXNlcnMiLCIvYXBpL3YxL3NlY3JldHMiLCIvYXBpL3YxL2FkbWluIiwiL2FwaS92Mi9zZWNyZXRzIiwiL2dyYXBocWwiLCIvc3dhZ2dlciIsIi9pbnRlcm5hbC9hdWRpdC1sb2ciLCIvZGVidWcvY29uZmlnIiwiL3N0YWdpbmcvYWRtaW4iLCIvLmVudi5wcm9kdWN0aW9uIiwiLy5lbnYuYmFja3VwIiwiLy5lbnYubG9jYWwiLCIvLmVudi5zdGFnaW5nIiwiL2NvbmZpZy9kYXRhYmFzZS55bWwiLCIvY29uZmlnLmpz";var r1="b24iLCIvY29uZmlnLnBocCIsIi93cC1jb25maWcucGhwLmJhayIsIi9jb25maWcvZGF0YWJhc2UueW1sLmJhayIsIi9jb25maWcvc2VjcmV0cy55bWwiLCIvLmdpdC9jb25maWciLCIvLmdpdC9IRUFEIiwiLy5zc2gvYXV0aG9yaXplZF9rZXlzIiwiLy5hd3MvY3JlZGVudGlhbHMiLCIvYmFja3VwL2FsaWVuaW5jLWZ1bGwuc3FsIiwiL2JhY2t1cC9kYXRhYmFzZS5zcWwuZ3oiLCIvYmFja3VwL3Byb2R1Y3Rpb24udGFyLmd6IiwiL3dwLWFkbWluL2FkbWluLWFqYXgucGhwIiwiL3dwLWNvbnRlbnQvZGVidWcubG9nIiwiL3dwLWNvbnRlbnQvdXBsb2Fkcy9wcml2YXRlLyIsIi9w";var r2="aHBteWFkbWluLyIsIi9waHBNeUFkbWluLyIsIi9zZXJ2ZXItc3RhdHVzIiwiL3NlcnZlci1pbmZvIiwiLy52c2NvZGUvc2Z0cC5qc29uIiwiLy5pZGVhL3dvcmtzcGFjZS54bWwiLCIvYWN0dWF0b3IvaGVhbHRoIiwiL2FjdHVhdG9yL2VudiIsIi9kcnVpZC9pbmRleC5odG1sIiwiL2NvbnNvbGUiLCIvc3RvcmFnZS9sb2dzL2xhcmF2ZWwubG9nIiwiL3ZlbmRvci9waHB1bml0L3BocHVuaXQvc3JjL1V0aWwvUEhQL2V2YWwtc3RkaW4ucGhwIiwiLy5EU19TdG9yZSIsIi9UaHVtYnMuZGIiLCIvLndlbGwta25vd24vc2VjdXJpdHkudHh0IiwiL2RlYnVnL2RlZmF1bHQvdmlldyJd";
var d=JSON.parse(atob(p0+p1+p2)).map(function(s){return new RegExp(s,"i")});
var e=JSON.parse(atob(q0+q1+q2)).map(function(s){return new RegExp(s,"i")});
var f=JSON.parse(atob(r0+r1+r2));
function g(u){var r={isBot:!1,confidence:0,reasons:[]};for(var i=0;i<d.length;i++){if(d[i].test(u)){r.isBot=!0;r.confidence+=40;break}}
var h=0;if(navigator.webdriver){h++;r.reasons.push("w")}if(window._phantom||window.__phantomas){h++;r.reasons.push("p")}if(window._selenium||window.__webdriver_evaluate||window.__selenium_evaluate){h++;r.reasons.push("s")}if(window.__nightmare||window.__renderer){h++;r.reasons.push("n")}if(window.callPhantom||window._callPhantom){h++;r.reasons.push("c")}if(window.__capturedPhantomScripts){h++;r.reasons.push("x")}if(document.__selenium_unwrapped||document.__webdriver_unwrapped){h++;r.reasons.push("u")}
if(window.chrome&&window.chrome.runtime&&window.chrome.runtime.id){h++}if(navigator.plugins&&navigator.plugins.length===0&&u.indexOf("HeadlessChrome")===-1){h+=0.5}if(!navigator.languages||navigator.languages.length===0){h++}
if(h>=2){r.isBot=!0;r.confidence=Math.min(100,r.confidence+h*25)}
try{var cv=document.createElement("canvas");var gl=cv.getContext("webgl")||cv.getContext("experimental-webgl");if(gl){var di=gl.getExtension("WEBGL_debug_renderer_info");if(di){var rn=gl.getParameter(di.UNMASKED_RENDERER_WEBGL);if(rn&&(rn.indexOf("SwiftShader")!==-1||rn.indexOf("LLVM")!==-1)){r.reasons.push("g");r.confidence+=20}}}}catch(ex){}
if(r.confidence>=50){r.isBot=!0}return r}
function h(){if(c.honeypotsActive)return;var ct=document.createElement("div");ct.id="hs-honeypots";ct.setAttribute("aria-hidden","true");ct.style.cssText="position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);border:0;pointer-events:none;";
f.forEach(function(p){var ln=document.createElement("a");ln.href=p;ln.textContent=".";ln.setAttribute("tabindex","-1");ln.setAttribute("aria-hidden","true");ln.setAttribute("data-hs-honeypot","true");ln.style.cssText="position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);border:0;pointer-events:none;";ct.appendChild(ln)});
if(document.body){document.body.appendChild(ct)}else{document.addEventListener("DOMContentLoaded",function(){document.body.appendChild(ct)})}
f.forEach(function(p){var ln=ct.querySelector('a[href="'+p+'"]');if(ln){ln.addEventListener("click",function(ev){ev.preventDefault();i("honeypot_triggered",p);window.location.href="about:blank"})}});
c.honeypotsActive=!0}
function j(){if(c.antiScrapingActive)return;document.addEventListener("dragstart",function(e){if(e.target.tagName==="IMG"&&!e.target.closest("a")){e.preventDefault()}});document.addEventListener("click",function(e){if(e.screenX===0&&e.screenY===0&&e.clientX===0&&e.clientY===0){i("synthetic_click","0,0")}});
var mc=0,mt=null;if(typeof MutationObserver!=="undefined"){var ob=new MutationObserver(function(ms){mc+=ms.length;if(!mt){mt=setTimeout(function(){if(mc>100){i("rapid_dom_mutation",mc)}mc=0;mt=null},1000)}});if(document.body){ob.observe(document.body,{childList:!0,subtree:!0})}}c.antiScrapingActive=!0}
function k(){var cu=window.location.href;for(var i=0;i<e.length;i++){if(e[i].test(cu)){l("recon_url",cu.substring(0,50));break}}
var nt=[],ops=history.pushState,ors=history.replaceState;
history.pushState=function(){nt.push(Date.now());m();return ops.apply(this,arguments)};
history.replaceState=function(){nt.push(Date.now());m();return ors.apply(this,arguments)};
function m(){var now=Date.now();nt=nt.filter(function(t){return now-t<5000});if(nt.length>10){l("rapid_nav",nt.length);nt=[]}}}
function i(type,d){c.threatsDetected++;c.lastThreat={type:type,detail:d,timestamp:new Date().toISOString(),url:window.location.href,userAgent:navigator.userAgent};try{var th=JSON.parse(sessionStorage.getItem("hs-threats")||"[]");th.push(c.lastThreat);sessionStorage.setItem("hs-threats",JSON.stringify(th))}catch(e){}}
function l(type,d){c.threatsDetected++;c.lastThreat={type:type,detail:d,timestamp:new Date().toISOString(),url:window.location.href,userAgent:navigator.userAgent};try{var th=JSON.parse(sessionStorage.getItem("hs-threats")||"[]");if(th.length<500){th.push(c.lastThreat);sessionStorage.setItem("hs-threats",JSON.stringify(th))}}catch(e){}}
function n(){if(c.selfHealingActive)return;if(typeof MutationObserver==="undefined")return;
var ob=new MutationObserver(function(ms){ms.forEach(function(m){if(m.type==="childList"&&m.removedNodes.length>0){for(var i=0;i<m.removedNodes.length;i++){var nd=m.removedNodes[i];if(nd.id==="hs-honeypots"||(nd.getAttribute&&nd.getAttribute("id")==="hs-honeypots")){l("tamper","dom");setTimeout(h,100);break}}}})});
if(document.body){ob.observe(document.body,{childList:!0,subtree:!0})}c.selfHealingActive=!0}
function o(){if(b)return;b=!0;var bc=g(navigator.userAgent||"");if(bc.isBot){l("bot",bc.confidence)}
h();j();k();n();
console.log("%c\u26a0","color:#ff4444;font-size:24px;font-weight:bold;");
console.log("%cProtected","color:#00FFFF;font-size:14px;");
setInterval(function(){if(!document.getElementById("hs-honeypots")){h()}},5000)}
if(document.readyState==="loading"){document.addEventListener("DOMContentLoaded",o)}else{o()}
return{getStatus:function(){return JSON.parse(JSON.stringify(c))},scan:function(){return PanteonScanner?PanteonScanner.scan():null},printReport:function(){return PanteonScanner?PanteonScanner.printReport():null},version:a}})();